### PR TITLE
Add versioned user agent to the wrapper

### PR DESCRIPTION
**Pull request by janxious**
@markushausammann Thoughts on how to do this better? Seems like there should be a way for me to read the version from composer or read the version from somewhere else and put it in the composer json file.

Also changelog added!

### CODE REVIEW

**Comment by janxious** [comment]
Having read the user agent rfc, I agree re `/`. I will change that. I have also added the php version in just for fun. Thanks for the feedback!

**Comment by janxious** [comment]
@markushausammann Added a config class with the reporting config and version information. Thoughts?

**Comment by markushausammann** [comment]
I think introducing a final config class is a good idea at that point, but I would really like to inject it instead of introducing global state with a singleton.

**Comment by janxious** [comment]
I don't know if I'm convinced, but I'll give it a go and see if I prefer non-global (or am at least neutral).

**Comment by markushausammann** [comment]
I avoid global state and singletons as a habit, sooner or later it always leads to problems, introducing unneeded coupling, inhibiting testability. IMO 99.9% of cases better to inject an interface and keep everything open for mocking.

**Comment by janxious** [comment]
Now with less global config!

**Comment by netshade** [comment]
:+1:

**Pull request merged**
